### ISSUE TITLE
Exeption while drowning

### ISSUE THREAD

**Issue by Allstreamer** [the-h-team/myEssentials#25]
Received this error while drowning on the test server
(on teleport-coords branch)
did not use god command btw
```java
[22:42:00 ERROR]: Could not pass event EntityDamageEvent to myEssentials v1.0.0
java.lang.NullPointerException: Cannot invoke "java.util.UUID.equals(Object)" because "s.uuid" is null
        at com.github.sanctum.myessentials.util.moderation.PlayerSearch.look(PlayerSearch.java:99) ~[?:?]
        at com.github.sanctum.myessentials.listeners.EntityEventListener.onGodHit(EntityEventListener.java:86) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor85.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-783]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-783]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-783]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.16.5.jar:git-Paper-783]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callEvent(CraftEventFactory.java:257) ~[patched_1.16.5.jar:git-Paper-783]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1091) ~[patched_1.16.5.jar:git-Paper-783]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1073) ~[patched_1.16.5.jar:git-Paper-783]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:934) ~[patched_1.16.5.jar:git-Paper-783]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1123) ~[patched_1.16.5.jar:git-Paper-783]
        at net.minecraft.server.v1_16_R3.EntityLiving.damageEntity0(EntityLiving.java:1932) ~[patched_1.16.5.jar:git-Paper-783]
        at net.minecraft.server.v1_16_R3.EntityHuman.damageEntity0(EntityHuman.java:953) ~[patched_1.16.5.jar:git-Paper-783]
        at net.minecraft.server.v1_16_R3.EntityLiving.damageEntity(EntityLiving.java:1260) ~[patched_1.16.5.jar:git-Paper-783]
        at net.minecraft.server.v1_16_R3.EntityHuman.damageEntity(EntityHuman.java:870) ~[patched_1.16.5.jar:git-Paper-783]
        at net.minecraft.server.v1_16_R3.EntityPlayer.damageEntity(EntityPlayer.java:982) ~[patched_1.16.5.jar:git-Paper-783]
        at net.minecraft.server.v1_16_R3.EntityLiving.entityBaseTick(EntityLiving.java:402) ~[patched_1.16.5.jar:git-Paper-783]
        at net.minecraft.server.v1_16_R3.Entity.tick(Entity.java:530) ~[patched_1.16.5.jar:git-Paper-783]
        at net.minecraft.server.v1_16_R3.EntityLiving.tick(EntityLiving.java:2543) ~[patched_1.16.5.jar:git-Paper-783]
        at net.minecraft.server.v1_16_R3.EntityHuman.tick(EntityHuman.java:258) ~[patched_1.16.5.jar:git-Paper-783]
        at net.minecraft.server.v1_16_R3.EntityPlayer.playerTick(EntityPlayer.java:658) ~[patched_1.16.5.jar:git-Paper-783]
        at net.minecraft.server.v1_16_R3.PlayerConnection.tick(PlayerConnection.java:325) ~[patched_1.16.5.jar:git-Paper-783]
        at net.minecraft.server.v1_16_R3.NetworkManager.a(NetworkManager.java:408) ~[patched_1.16.5.jar:git-Paper-783]
        at net.minecraft.server.v1_16_R3.ServerConnection.c(ServerConnection.java:168) ~[patched_1.16.5.jar:git-Paper-783]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1515) ~[patched_1.16.5.jar:git-Paper-783]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:436) ~[patched_1.16.5.jar:git-Paper-783]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1342) ~[patched_1.16.5.jar:git-Paper-783]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1130) ~[patched_1.16.5.jar:git-Paper-783]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-783]
        at java.lang.Thread.run(Thread.java:831) [?:?]
```

**Comment by Allstreamer** [comment]
actually this happens on every tick of damage now
i'll continue testing

**Comment by ms5984** [comment]
Confirmed, when I finish up this branch shortly it should be resolved
