### ISSUE TITLE
/online having problems

### ISSUE THREAD

**Issue by Allstreamer** [the-h-team/myEssentials#27]
/online throws an exception

Steps to reproduce:
Start Paper-1.16.5 Server with Labyrinth-1.7.0-SNAPSHOT & Built master branch of myEssentials
Execute /online
Check console for error:
```java
[23:22:54 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'online' in com.github.sanctum.myessentials.model.CommandImpl(online)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:169) ~[patched_1.16.5.jar:git-Paper-783]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:826) ~[patched_1.16.5.jar:git-Paper-783]
        at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2185) ~[patched_1.16.5.jar:git-Paper-783]
        at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:2000) ~[patched_1.16.5.jar:git-Paper-783]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1953) ~[patched_1.16.5.jar:git-Paper-783]
        at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:49) ~[patched_1.16.5.jar:git-Paper-783]
        at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:7) ~[patched_1.16.5.jar:git-Paper-783]        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:35) ~[patched_1.16.5.jar:git-Paper-783]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Paper-783]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Paper-783]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Paper-783]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Paper-783]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1266) ~[patched_1.16.5.jar:git-Paper-783]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1259) ~[patched_1.16.5.jar:git-Paper-783]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Paper-783]
        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1220) ~[patched_1.16.5.jar:git-Paper-783]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1134) ~[patched_1.16.5.jar:git-Paper-783]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-783]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.UnsupportedOperationException: SuperPerms no group permissions.
        at net.milkbowl.vault.permission.plugins.Permission_SuperPerms.getPrimaryGroup(Permission_SuperPerms.java:96) ~[?:?]
        at net.milkbowl.vault.permission.Permission.getPrimaryGroup(Permission.java:679) ~[?:?]
        at com.github.sanctum.labyrinth.library.VaultPlayer.getGroup(VaultPlayer.java:46) ~[?:?]
        at com.github.sanctum.myessentials.commands.OnlineListCommand.playerView(OnlineListCommand.java:55) ~[?:?]
        at com.github.sanctum.myessentials.model.CommandImpl.execute(CommandImpl.java:51) ~[?:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.5.jar:git-Paper-783]
        ... 18 more
```

**Comment by Hempfest** [comment]
Thanks for testing! Its due to no permission plugin. Ill need to add an alt display for the instance of no perm plugin.

**Comment by Allstreamer** [comment]
Okay, i'm just running through all the commands right now, testing if everything works.
